version: '3'

services:
  db:
    restart: always
    image: "postgres:9.6.5"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env_file
    networks:
      - db_network

  flaskapp:
    restart: always
    build: .
    env_file:
      - env_file
    ports:
      - 8080:8080
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_network
      - web_network
    depends_on:
      - db

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - flaskapp

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  dbdata:
